- .hound.yml
- README.md
- config/.scss-style.yml
> adding-hound-configuration

- Gruntfile.js
- docs/_layouts/default.html
- docs/colors.md
- docs/docs.scss
- styles/colors.scss
- styles/nav.scss
- styles/side-menu.scss
> 94703-adding-complete-color-palette

- .gitignore
- Gruntfile.js
- _config.yml
- config.yml
- docs/_layouts/default.html
- gitignore
- package.json
- util/update-version.js
> manual-deploy-fixes

- docs/nav.md
- styles/nav.scss
> 92155-nav-bar-styling

- README.md
- docs/colors.md
> fixing duplicate colors and adding site to readme

- styles/nav.scss
> 92155-need-explicit-width-quirks-mode

- .gitignore
- .pullquester/pullrequest.json
- Gruntfile.js
- bower.json
- docs/docs.scss
- docs/nav.md
- package.json
- styles/nav.scss
- styles/side-menu.scss
> 95055-navigation-menu-tab

- docs/nav.md
- styles/nav.scss
- styles/variables.scss
> 95055-navigation-menu-dropdown

- docs/nav.md
- styles/nav.scss
- styles/variables.scss
> Revert "95055-navigation-menu-dropdown"

- docs/nav.md
- styles/nav.scss
- styles/variables.scss
Reverts Reverts daptiv/style-guide#21
> Revert "Revert "95055-navigation-menu-dropdown""

- README.md
- docs/nav.md
- package.json
- styles/nav.scss
Updated styles for overflow menu items.
> 95339-SeeAll-submenu-overflow-styling

- styles/base.scss
> 95084-fix-broken-styling-due-to-global-styles

- docs/nav.md
- styles/nav.scss
> 95918-add-sub-navigation-styles-to-style-guide

- .scss-lint.yml
- Gruntfile.js
- package.json
- styles/base.scss
- styles/layout.scss
- styles/nav.scss
- styles/side-menu.scss
- styles/style-guide.scss
- styles/type.scss
> adding-scss-lint

- styles/nav.scss
> 95055-nav-more-dropdown

- Gemfile
- Gruntfile.js
- docs/_plugins/snippet.rb
- docs/docs.scss
- docs/nav.md
- styles/nav.scss
> snippet-block-tag

- docs/nav.md
- styles/iconography.scss
- styles/nav.scss
> 94755-item-browser-subnav-visual-treatment

- docs/_layouts/default.html
- docs/colors.md
- docs/docs.scss
- docs/iconography.md
- gitignore
- package.json
- styles/_base.scss
- styles/_colors.scss
- styles/_side-menu.scss
- styles/dropdown/_styles.scss
- styles/dropdown/_variables.scss
- styles/nav/_styles.scss
- styles/nav/_variables.scss
- styles/panel/_styles.scss
> 97668-Final-colors-for-Brand-Alignment

- package.json
- styles/buttons/_styles.scss
> 97379-password-help-new-color-buttons

- package.json
- styles/buttons/_styles.scss
> Revert "97379-password-help-new-color-buttons"

- docs/_plugins/colorswatch.rb
- docs/colors.md
- docs/docs.scss
- docs/iconography.md
- package.json
- styles/_typography.scss
- styles/iconography/_styles.scss
> add-search-icon

- docs/colors.md
- docs/docs.scss
- package.json
- styles/_colors.scss
- styles/nav/_variables.scss
> add-font-alias-colors

- docs/_layouts/simple.html
- docs/colors.md
- docs/docs.scss
- package.json
- styles/_colors.scss
> add-medium-accent-font-color

- docs/_plugins/iconblock.rb
- docs/docs.scss
- docs/iconography.md
- package.json
- styles/iconography/_mixins.scss
- styles/iconography/_styles.scss
> 93143-workspace-actions

- docs/colors.md
- docs/docs.scss
- package.json
- styles/_colors.scss
> add-70-percent-grey-color

- docs/components.md
- package.json
- styles/buttons/_styles.scss
- styles/buttons/_variables.scss
> alternate-button-style

- docs/colors.md
- docs/docs.scss
- package.json
- styles/_colors.scss
> add-link-color-alias

- docs/_plugins/iconblock.rb
- docs/docs.scss
- docs/iconography.md
- package.json
- styles/iconography/_styles.scss
> user-and-help-icons

- package.json
- styles/nav/_mixins.scss
- styles/nav/_styles.scss
- styles/nav/_variables.scss
> extract-nav-tab-mixin

- styles/iconography/_styles.scss
> 99748-expandable-search

- styles/dropdown/_styles.scss
> 100800-add-white-space

- README.md
- docs/nav.md
- package.json
- styles/dropdown/_styles.scss
> 100527-add-name-to-user-menu

- bower.json
> clean-up-font-awesome

- styles/nav/_mixins.scss
> 100148-active-elements-gray-background-IE10

- Gruntfile.js
- docs/docs.scss
- docs/pygments-default-theme.css
- package.json
> remove-bower-dependency

- styles/_variables.scss
> border-thick

- docs/_layouts/simple.html
> 110604-make-theme-selection-sticky

- docs/components.md
- docs/iconography.md
- styles/_components.scss
- styles/_drop-down-list.scss
- styles/drop-down-list/_styles.scss
- styles/drop-down-list/_variables.scss
- styles/iconography/_styles.scss
> 108760-switch-filters

- styles/themes/teammember/_variables.scss
Fixed the import font-awesome reference for team member themes variables.
> Fixed Import Reference for Font Awesome in Team Member Themes Variables

- docs/components.md
- styles/drop-down-list/_styles.scss
> 112524-filter-selector-positioning

- .csscomb.json
- .scss-lint.yml
- docs/components.md
- styles/_buttons.scss
- styles/_card.scss
- styles/_colors.scss
- styles/_components.scss
- styles/_typography.scss
- styles/buttons/_mixins.scss
- styles/card/_styles.scss
- styles/card/_variables.scss
- styles/drop-down-list/_styles.scss
- styles/layout/_styles.scss
> 112632-task-card-styling

- styles/layout/_styles.scss
> 112622-fix-box-shadow-header

- .gitignore
- docs/_docs-base.scss
- docs/components.md
- styles/drop-down-list/_styles.scss
- styles/drop-down-list/_variables.scss
> 112625-subheader-fit-finish

- docs/_layouts/simple.html
- docs/components.md
- styles/drop-down-list/_styles.scss
- styles/side-bar/_styles.scss
105472
run:
```
git pull
npm publish
```
> 105472-use-open-close-container

- docs/components.md
- styles/drop-down-list/_styles.scss
105472
run:
```
git pull
npm publish
```
> 105472-dropdown-selected-state

- docs/_docs-base.scss
- docs/colors.md
- docs/iconography.md
- styles/_colors.scss
- styles/iconography/_styles.scss
- styles/iconography/_variables.scss
105472
run:
```
git pull
npm publish
```
> 105472-add-error-circle

- styles/_animations.scss
- styles/loading-indicator/_styles.scss
108744
run:
```
git pull
npm publish
```
> 108744-fix-animations

- styles/_colors.scss
- styles/_typography.scss
105472
run:
```
git pull
npm publish
```
> 105472-code-review-fixes

- .travis.yml
run:
```
git pull
npm publish
```
> add-travis-ci

- styles/buttons/_mixins.scss
113254
run:
```
git pull
npm publish
```
> 113254-fixing-tap-highlighting

- package.json
run:
```
git pull
npm publish
```
> making-font-awesome-peer-dependency

- styles/card/_styles.scss
run:
```
git pull
npm publish
```
> fix-card-flag-filters

- .pullquester/pullrequest.json
- .travis.yml
- styles/iconography/_styles.scss
run:
```
git pull
npm publish
```
> 113797 add exclamation triangle icon

- docs/_includes/guidemenu.html
- docs/components.md
- styles/_side-menu.scss
Moved daptiv-side-menu item, readonly, divider classes inside daptiv-side-menu 
run:
```
git pull
npm publish
```
> 119657-120727-simplify-daptiv-side-menu-child-styles

- docs/components.md
- styles/card/_styles.scss
- styles/card/_variables.scss
run:
```
git pull
npm publish
```
> card-status-full-width

- styles/card/_styles.scss
121548
run:
```
git pull
npm publish
```
> 121548-long-names-push-out-flags

- docs/iconography.md
- styles/buttons/_styles.scss
- styles/iconography/_styles.scss
- styles/themes/teammember/_component-overrides.scss
- styles/themes/teammember/_variables.scss
105469
run:
```
git pull
npm publish
```
> 105469-add-tm-button

- docs/colors.md
- docs/site-styles/swatch/_styles.scss
- styles/_colors.scss
added colors for the project grouping header
run:
```
git pull
npm publish
```
> 120371-project-grouping-styling-updates

- docs/_docs-base.scss
- docs/_includes/guidemenu.html
- docs/_plugins/font-block.rb
- docs/site-styles/typography/_styles.scss
- docs/typography.md
- styles/_typography.scss
run:
```
git pull
npm publish
```
> add-typography-to-docs

- docs/colors.md
- docs/site-styles/swatch/_styles.scss
- styles/_colors.scss
- styles/card/_styles.scss
- styles/card/_variables.scss
- styles/themes/teammember/_component-overrides.scss
123257
run:
```
git pull
npm publish
```
> 123257-flag-design

- .pullquester/pullrequest.json
- styles/side-bar/_styles.scss
123257
run:
```
git pull
npm publish
```
> 123257-flatten-side-bar

- docs/colors.md
- docs/site-styles/swatch/_styles.scss
- styles/_colors.scss
- styles/_typography.scss
121916
run:
```
git pull
npm publish
```
> 121916-failed-time-entry

- styles/card/_styles.scss
123257
run:
```
git pull
npm publish
```
> 123257-removing-min-height-card

- docs/colors.md
- docs/iconography.md
- docs/site-styles/swatch/_styles.scss
- styles/_colors.scss
- styles/iconography/_styles.scss
122424
run:
```
git pull
npm publish
```
> 122424-like-dont-like-feedback

- styles/card/_styles.scss
- styles/card/_variables.scss
- styles/iconography/_styles.scss
127238
run:
```
git pull
npm publish
```
> 127238-dense-ttm

- styles/card/_styles.scss
> reduce flag size

- docs/components.md
- styles/card/_styles.scss
- styles/layout/_styles.scss
133707
run:
```
git pull
npm publish
```
> 133707-new-task-card-layout

- styles/iconography/_styles.scss
133707
run:
```
git pull
npm publish
```
> 133707-remove-flag-flip
